// vRM_Languages.h
//
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef __VRM_LANGAUAGES_H__
#define __VRM_LANGAUAGES_H__

    /*********************************************************
     **               C O N F I D E N T I A L               **
     **                  Copyright ® 2010                   **
     **    Red Bend Software Inc.    All rights reserved    **
     *********************************************************/ 


typedef enum {VRM_Test = 0,
VRM_UK_English,
VRM_French,
VRM_German,
VRM_Spanish,
VRM_Italian,
VRM_Swedish,
VRM_Danish,
VRM_Norwegian,
VRM_Finnish,
VRM_American_English,
VRM_Swiss_French,
VRM_Swiss_German,
VRM_Portuguese,
VRM_Turkish,
VRM_Icelandic,
VRM_Russian,
VRM_Hungarian,
VRM_Dutch,
VRM_Belgian_Flemish,
VRM_Australian,
VRM_Belgian_French,
VRM_Austrian,
VRM_New_Zealand,
VRM_International_French,
VRM_Czech,
VRM_Slovak,
VRM_Polish,
VRM_Slovenian,
VRM_Chinese_Taiwan,
VRM_Chinese_Hong_Kong,
VRM_Chinese_PRC,
VRM_Japanese,
VRM_Thai,
VRM_Afrikaans,
VRM_Albanian,
VRM_Amharic,
VRM_Arabic,
VRM_Armenian,
VRM_Tagalog,
VRM_Belarussian,
VRM_Bengali,
VRM_Bulgarian,
VRM_Burmese,
VRM_Catalan,
VRM_Croatian,
VRM_Canadian_English,
VRM_International_English,
VRM_South_African_English,
VRM_Estonian,
VRM_Farsi,
VRM_Canadian_French,
VRM_Scots_Gaelic,
VRM_Georgian,
VRM_Greek,
VRM_Cyprus_Greek,
VRM_Gujarati,
VRM_Hebrew,
VRM_Hindi,
VRM_Indonesian,
VRM_Irish,
VRM_Swiss_Italian,
VRM_Kannada,
VRM_Kazakh,
VRM_Khmer,
VRM_Korean,
VRM_Lao,
VRM_Latvian,
VRM_Lithuanian,
VRM_Macedonian,
VRM_Malay,
VRM_Malayalam,
VRM_Marathi,
VRM_Moldavian,
VRM_Mongolian,
VRM_Norwegian_Nynorsk,
VRM_Brazilian_Portuguese,
VRM_Punjabi,
VRM_Romanian,
VRM_Serbian,
VRM_Sinhalese,
VRM_Somali,
VRM_International_Spanish,
VRM_Latin_American_Spanish,
VRM_Swahili,
VRM_Finland_Swedish,
VRM_Tajik,
VRM_Tamil,
VRM_Telugu,
VRM_Tibetan,
VRM_Tigrinya,
VRM_Cyprus_Turkish,
VRM_Turkmen,
VRM_Ukrainian,
VRM_Urdu,
VRM_Uzbek,
VRM_Vietnamese,
VRM_Welsh,
VRM_Zulu,
VRM_Other,
VRM_Manfacturer_English,
VRM_South_Sotho,
VRM_English_APAC = 129,
VRM_English_APAC_Taiwan = 157,
VRM_English_APAC_HongKong,
VRM_English_APAC_PRC,
VRM_English_APAC_Japanese,
VRM_English_APAC_Thai,
VRM_Malai_APAC,
VRM_NO_LANG = 0xffff
} vRM_Languages;


#endif // __VRM_LANGAUAGES_H__
