#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y				+= strobe_main_sid2_part1.o
obj-y   +=  constant_flashlight/




